# Generated by Django 5.2.1 on 2025-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
