# Generated by Django 5.2.1 on 2025-05-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_playlist_last_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='color',
            field=models.CharField(choices=[('black', 'Черный'), ('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('green', 'Зеленый'), ('blue', 'Синий'), ('indigo', 'Индиго'), ('violet', 'Фиолетовый'), ('gray', 'Серый'), ('pink', 'Розовый'), ('cyan', 'Бирюзовый'), ('teal', 'Морской волны'), ('lime', 'Лайм'), ('brown', 'Коричневый'), ('maroon', 'Бордовый'), ('navy', 'Темно-синий'), ('olive', 'Оливковый'), ('gold', 'Золотой'), ('silver', 'Серебристый'), ('white', 'Белый')], default='black', max_length=20),
        ),
    ]
