# Generated by Django 5.2.1 on 2025-06-17 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlist_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='color',
            field=models.CharField(choices=[('#a8a8a8', 'Серый'), ('#e57373', 'Красный'), ('#ffb74d', 'Оранжевый'), ('#fff176', 'Желтый'), ('#81c784', 'Зелёный'), ('#64b5f6', 'Синий'), ('#7986cb', 'Индиго'), ('#ba68c8', 'Фиолетовый'), ('#f06292', 'Розовый'), ('#4dd0e1', 'Бирюзовый'), ('#4db6ac', 'Морской волны'), ('#dce775', 'Лайм'), ('#a1887f', 'Коричневый'), ('#ce93d8', 'Сиреневый'), ('#90caf9', 'Темно-синий (navy)'), ('#c5e1a5', 'Оливковый'), ('#ffd54f', 'Золотой'), ('#b0bec5', 'Серебристый'), ('#eeeeee', 'Светло-серый')], default='black', max_length=20),
        ),
        migrations.CreateModel(
            name='FavoriteWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='playlist.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
