# Generated by Django 5.2.1 on 2025-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_alter_playlist_color_favoriteword'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.CharField(choices=[('DE', 'DE'), ('EN', 'EN')], default='EN', max_length=3),
        ),
    ]
